name: KMP Weather App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# On utilise NODE24 pour les actions, la version 20 est déprécié.
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    # 2. L'environnement : On utilise un serveur Ubuntu (plus rapide et moins cher).
    # Note : Si on voulait tester spécifiquement iOS, on utiliserait 'macos-latest'.
    runs-on: ubuntu-latest

    steps:
      # Étape A : Le serveur télécharge ton code
      - name: Checkout du code
        uses: actions/checkout@v4

      # Étape B : On installe l'environnement Java nécessaire à Android/Kotlin
      - name: Configuration de Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Étape C : Optimisation du cache Gradle pour accélérer les futurs builds
      - name: Configuration de Gradle
        uses: gradle/actions/setup-gradle@v3

      # Étape D : La permission d'exécution
      - name: Rendre gradlew exécutable
        run: chmod +x gradlew

      # Étape E : La vérification (Tests Unitaires et Linting)
      - name: Lancement des Tests
        run: ./gradlew check

      # Étape F : Déploiement continu (Génération de l'application)
      - name: Build de l'APK Android
        run: ./gradlew assembleDebug

      # Étape G : Sauvegarde (On met l'APK à disposition pour le téléchargement)
      - name: Sauvegarde de l'APK (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: weather-app-debug
          path: '**/*.apk'